# Generated by Django 4.2.7 on 2023-11-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='username',
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
