# Generated by Django 4.2.7 on 2023-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='artistbio',
            options={'verbose_name': 'Artist Bio', 'verbose_name_plural': 'Artist Bio'},
        ),
        migrations.AlterModelOptions(
            name='featuredartists',
            options={'verbose_name': 'Featured Artist', 'verbose_name_plural': 'Featured Artists'},
        ),
        migrations.AlterModelOptions(
            name='upcomingevents',
            options={'verbose_name': 'Upcoming Event', 'verbose_name_plural': 'Upcoming Events'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profession',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('current', 'Current Works'), ('previous', 'Previous Works')], default='current', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
