# Generated by Django 4.2.7 on 2023-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
