# Generated by Django 4.2.7 on 2023-11-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0003_featuredartists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredartists',
            name='selected_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistsmgmt.portfolio'),
        ),
    ]
