# Generated by Django 4.2.7 on 2023-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0003_alter_portfolio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
