# Generated by Django 4.2.7 on 2023-12-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0003_upcomingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('expert_level', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bio_photos/')),
                ('description', models.TextField()),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artistsmgmt.artist')),
            ],
        ),
    ]
