# Generated by Django 4.2.7 on 2023-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0004_alter_featuredartists_selected_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredartists',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
