# Generated by Django 4.2.7 on 2023-12-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistsmgmt', '0004_artist_photo_artist_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('visual artists', 'Visual Artists'), ('performing artists', 'Performing Artists'), ('literary artists', 'Literary Artists'), ('fashion artists', 'Fashion Artists')], default='', max_length=100),
        ),
    ]
